### ISSUE TITLE
Implement Medication Details Screen

### ISSUE THREAD

**Issue by DevSchmidtchen** [hpi-dhc/PharMe#102]
## Medication details screen MVP

See #199 for discussion of process.

### Front-end

- #87 
- #208 
- #215
- #113 

### Back-end

- #193 
- #213
- #214
- #256 
- #258 
- ~~#251~~
- #252

**Comment by dieknolle3333** [comment]
![annotation_server_db](https://user-images.githubusercontent.com/57364771/163352467-9cf23d61-9fb2-4a52-8f07-3939e01925e2.svg)

**Comment by dieknolle3333** [comment]
![annotation_server_db_er](https://user-images.githubusercontent.com/57364771/164075592-1db685cc-ac03-4e87-a20d-a36a7ef14419.png)

**Comment by dieknolle3333** [comment]
![annotation_server_db_er](https://user-images.githubusercontent.com/57364771/164077739-c2a7174d-afb3-4c86-a7c1-900648c8cc80.svg)

**Comment by dieknolle3333** [comment]
> ![annotation_server_db_er](https://user-images.githubusercontent.com/57364771/164077739-c2a7174d-afb3-4c86-a7c1-900648c8cc80.svg)

guideline now has a warning level
