### ISSUE TITLE
Interview Medical Professionals

### ISSUE THREAD

**Issue by dieknolle3333** [hpi-dhc/PharMe#171]
## learnings
(that might seem self-evident but are really important)
coduct it as a pair: one person leading the interview, the other one writing it down
alternativerly, record it on zoom (has to be done in the settings on UP Zooms site)
be prepared: be in the call 5 mins early and set up drive to make notes and youtube to show video
in brave, I have to share my chrome tab to share the sound
## to dos
- [x] include jonathans feedback

**Comment by SebastianWagner2** [comment]
Not relevant anymore
