### ISSUE TITLE
Add meaningful information for PGx

### ISSUE THREAD

**Issue by LeonHermann322** [hpi-dhc/PharMe#204]
Add information for PGx into the PGx-tab in the Figma prototype.

**Comment by dieknolle3333** [comment]
# first ideas
## PGx
> What is Pharmacogenomics? (
> What makes Pharmacogenomics relevant to me?
> Which drugs are affected?
## PharMe
> What does PharMe do?
> Where does PharMe get its data?
> Is my personal data safe?
> Can I use PharMe's results without consulting a medical professional?

**Comment by dieknolle3333** [comment]
watch google doc
