### ISSUE TITLE
Fetch supplemental CPIC data

### ISSUE THREAD

**Issue by jannis-baum** [hpi-dhc/PharMe#213]
> Belongs to epic #102. Partly dependent on #193.

- [x] fetch all CPIC recommendations & organize by medications and `lookupkey`s analogous to Google Sheet data from #193
- [ ] use CPIC data to verify completeness of Google Sheet and notify someone somehow if it isn't complete (see #252)
- [ ] ~~discuss which supplemental data we want to provide for the normal medication detail screen (e.g. Aniwaa's suggestion of showing diplotype frequency across population groups)~~\
  add supplemental data: frequency of phenotype across population groups and implement into endpoint from #193 accordingly
- [ ] add raw CPIC recommendations to existing database for new endpoint that can be used for PDF export

**Comment by dieknolle3333** [comment]
just making sure I understood correctly: do we only fetch the medications present in the Google sheet? Because at the moment, a lot of meds are missing. If I understood correctly, all of CPIC's medications are supposed to be present in the Google sheet later on, right? At that point, we should be querying all meds, as we can then alert someone if a drug is missing from the Google sheet

**Comment by dieknolle3333** [comment]
Actually, in the meantime, a lot of gene-drug pairs were added, so it's definitely not missing "a lot" of meds any more. Nevertheless, if I query ``https://api.cpicpgx.org:443/v1/pair_view?guidelinename=not.is.null&guidelineurl=not.is.null`` I receive 139 drug-gene pairs with a guideline. In the current table, 108 rows are filled, about 15 without any genes, and about 9 with two genes (all just rough counts). So I guess about 37 gene-drug pairs are missing as of right now. 
My premise is that we want to have every drug-gene pair with a guideline in the table. Is that correct?

**Comment by jannis-baum** [comment]
Interesting! I'm not entirely sure whether the premise is correct though since I haven't looked into how exactly CPIC *guidelines* map to their *recommendations* in terms of quantity. I think it would be fair to take the following as a premise:

> Each of CPICs *recommendations* should equate to one medication-gene-phenotype pair in the table.

CPIC recommendations are available through the `recommendation`, `recommendation_view` and `recommendation_lookup` endpoints. On the sheet's side of things, each row can have a variable number of recommendations depending on how many cells between columns `N` and `V` (or `W` and `AE`, which should be the same number) not equal to `N/A` it has.

**Comment by dieknolle3333** [comment]
Todo: squash commits and add Matti as co-author!
