### ISSUE TITLE
Add unit tests

### ISSUE THREAD

**Issue by jannis-baum** [hpi-dhc/PharMe#235]
unit tests for #193

**Comment by dieknolle3333** [comment]
decided against writing unit tests for ``guideline.service.ts``, as integration tests would be easier to write and as the needed repositories in the other modules (e.g. MedicationsModule) are hard to mock. Next to that, it seems reasonable to say that only the public interface of a class should be tested, e.g. [here](https://enterprisecraftsmanship.com/posts/unit-testing-private-methods/) and [here](https://softwareengineering.stackexchange.com/questions/100959/how-do-you-unit-test-private-methods).
