### ISSUE TITLE
Setup Storage Bucket for Annotation Server

### ISSUE THREAD

**Issue by Benjamin-Frost** [hpi-dhc/PharMe#29]
We need some kind of Storage Bucket for e.g. images. In a real world application something like AWS S3 would be used. As an alternative we could use [MinIO](https://github.com/minio/minio)

[Example Implementation](https://betterprogramming.pub/upload-and-retrieve-images-by-integrating-minio-with-nestjs-419e4e629b5d)

**Comment by jannis-baum** [comment]
No longer needed
