### ISSUE TITLE
Detail screen without guidelines

### ISSUE THREAD

**Issue by dieknolle3333** [hpi-dhc/PharMe#360]
We need to discuss how the detail screen looks in case there are no guidelines for a user's phenotype for the shown medication.
As of right now, the disclaimer text does not seem to fit in this case, see picture below. 
![image](https://user-images.githubusercontent.com/57364771/172933030-210b208f-c7f9-47c4-bf1a-f9eb82a23956.png)

- [ ] discuss text for disclaimer
- [ ] discuss layout for disclaimer
- [ ] add it to Figma prototype?
- [ ] implement it

**Comment by tamslo** [comment]
@jannis-baum I think this is part of your current implementations, isn't it? 🙂

**Comment by jannis-baum** [comment]
@tamslo True! This was implemented by #447
