### ISSUE TITLE
Optimize Memory Usage of annotation server initialization

### ISSUE THREAD

**Issue by DevSchmidtchen** [hpi-dhc/PharMe#376]
We are using the python package [xmltodict](https://github.com/martinblech/xmltodict) to parse the drugbank xml to a dictionary and then write it into a JSON-file. This works, but uses a lot of memory. Maybe we can optimize the memory usage through streaming etc. (xmltodict itself has a streaming mode).

**Comment by jannis-baum** [comment]
#402 adds a script to create a minimized DrugBank XML. Using such a minimized version voids the issue of too much memory usage. This issue is kept open nonetheless since it would be preferred to have it *✨just work✨* without needing to use some other script in preparation.

**Comment by jannis-baum** [comment]
The python library that is currently used to parse the XML also allows streaming data, see [*Streaming mode*](https://pypi.org/project/xmltodict/). This in addition to writing a JSON in streaming mode or switching to multiple JSONs would solve the problem.

**Comment by jannis-baum** [comment]
Closing since Annotation Server was deleted in #526
