### ISSUE TITLE
`anni`: update CPIC data before starting curating

### ISSUE THREAD

**Issue by tamslo** [hpi-dhc/PharMe#458]
Aniwaa notified us that [a new CPIC version](https://github.com/cpicpgx/cpic-data/releases/tag/v1.21.0) was released. This version should be used for the annotation server.

**Comment by tamslo** [comment]
We do not need to react to every update; should maybe update once before curating guidelines

**Comment by jannis-baum** [comment]
Will be unavoidable anyways
