### ISSUE TITLE
Private app data endpoint

### ISSUE THREAD

**Issue by jannis-baum** [hpi-dhc/PharMe#532]
- If content should be private (public would be okay but private preferred from Aniwaa's side):
    - Current idea: send encrypted request-index or some other key to avoid replay attack
    - Is it possible to make a secret request from the app to fetch data? If so, how? (@tamslo asking Thomas) ➡ if secret in app not really safe but better than nothing; could use keycloak
- Can we include some license (e.g., attribution)?
- Can we have `<host>/api/v1` open and everything else closed?

**Comment by tamslo** [comment]
Using Keycloak in study backend (only on Sinai remote)
