### ISSUE TITLE
Logo Survey

### ISSUE THREAD

**Issue by DevSchmidtchen** [hpi-dhc/PharMe#98]
- [x] Collect Logo Ideas/Sketches
- [x] Illustrate Logo
- [x] Prepare Survey
- [x] German Translation @dieknolle3333 
- [ ] Send logo survey around to friends, family, etc.

[Survey link](https://forms.gle/7i72hB7hX5AjmTHu8)

**Comment by Toalaah** [comment]
Close on 14th of Apr.
